// Code generated by generator, DO NOT EDIT.
package example

import domain "github.com/gospodinzerkalo/gokit-codegen/domain"

func (c store) CreateUser(d domain.User) (*domain.User, error) {
	if _, err := c.db.Exec("INSERT INTO users (name) VALUES ($1)", d.Name); err == nil {
		return nil, err
	}
	return &d, nil
}
